### PR TITLE
Highlights content title if it is left as the default #116

### PR DESCRIPTION
**Pull request by voodoochild**

### CODE REVIEW

**Comment by tivac** [comment]
Should we even store a default title in FireBase? Maybe that should be auto-generated within the CMS UI and then highlighted if it had to be generated? Maybe it's an annoying change if you aren't really using the title field, but even then it's how it's identified in the CMS so it should probably be something worthwhile.

Wonder what @kevinkace thinks.

**Comment by voodoochild** [comment]
My leaning on this is to keep the default given that, as you say, the title is currently being used in the UI to identify which piece of content you're looking at. Would definitely be interesting to see how it's being used in the two(?) live applications so far.

**Comment by tivac** [comment]
The CMS would use something like

> (Untitled <x>)

where `<x>` is the content type, most likely. It could generate that within the views using a shared `title()` function and it would simplify the logic necessary for highlighting the titled field. I just don't know that I see much value in storing generated data in firebase if it doesn't provide any value.

**Comment by kevinkace** [comment]
Hmm, not sure I have a strong opinion.

What are the use-cases? To inform the content editor that the title is not set? `Untitled <x>` works. Focused/highlighted seems handy too.

Unique titles are no longer planned as they've been replaced with unique slugs?

**Comment by tivac** [comment]
Yeah there's no intent to enforce title uniqueness.

For me it mostly comes down to one of these two options.

1. Leave as-is, where the CMS generates a fake title and sticks it into Firebase
2. Don't store a fake title in Firebase and have the CMS frontend create one where necessary

I like option 2 because it makes detecting an unset title trivial and means we aren't storing "fake" data in Firebase. Why I care about I'm not sure, but it feels better to the lizard part of my brain.

**Comment by voodoochild** [comment]
Sounds sane to me. I'll update my pull request so that we're no longer storing "New <thing>", and will change it to display "Untitled <thing>" in the UI instead. I'm thinking that we keep the highlight/focus since it's arguably good practice to set a title for id purposes if nothing else.

**Comment by tivac** [comment]
@voodoochild :+1: Agreed that it should still focus/highlight the field if there isn't a title set.

**Comment by voodoochild** [comment]
I'm having a brainfart looking at implementing this in that the slug is always generated from the name attribute. What should the logic be if no name has been set?

**Comment by tivac** [comment]
Empty?

**Comment by tivac** [comment]
Landed in b0e73114c71dff44d41a3f71b78ce396285e42ce but I fucked it up a bit while merging.

Git :disappointed:

Thanks Kriss!

**Pull request closed without merging**
